import { StyleSheet } from 'react-native';
const styles = StyleSheet.create({
    screen2Container: {
    height: '60%',
    position: 'relative',
    flex: 1,
    flexDirection: 'column',
    width: '100%',
    // borderWidth: 3,
    // borderColor: 'red',
    alignItems: 'center',
    justifyContent: 'center',
    },
    castingbox: {
        width: '100%',
        // borderWidth: 4,
        // borderColor: 'white',
        flex: 2,
        marginTop: 20,
        justifyContent: 'center',
        alignItems: 'center',
      },
      SliderContainer: {
        width: '100%',
        // borderWidth: 4,
        // borderColor: 'yellow',
        flex: 2,
        justifyContent: 'center',
        alignItems: 'center',
        position: 'relative',
        flexDirection: 'row',
      },
      avatarContainer: {
        margin: 20,
        width: 100,
        height: 100,
        borderRadius: 50,
        borderWidth: 2,
        borderColor: 'yellow',
        justifyContent: 'center',
        alignItems: 'center',
      },
      AvatarImg: {
        width: 96,
        height: 96,
        borderRadius: 48,
      },
      CastingInfo: {
        flex: 2,
        height: '100%',
        // borderWidth: 4,
        // borderColor: 'green',
        flexDirection:  'column',
      },
      name: {
        // width: '20%',
        flex: 1,
        // height: '20%',
        // borderWidth: 3,
        // borderColor: 'white',
        fontSize: 32,
        color: 'yellow',
        fontFamily: 'Comfortaa',
        fontStyle: 'normal',
        paddingVertical: 10,
        textAlign: 'center',
        // position: 'absolute',
        // color: 'white',
        // fontSize: 20,
        // top: '50%',
        // left: '37%',
        // transform: [{ rotate: '-15deg' }],

      },
      LastName: {
        flex: 1,
        fontSize: 20,
        color: 'white',
        textAlign: 'center',
      },
      castingtxt: {
        color: 'yellow',
        fontSize: 26,
        // width: '60%',
        // marginLeft: 50,
        flex: 1,
        // height: '20%',
        // borderWidth: 3,
        // borderColor: 'purple',
        // transform: [{ rotate: '-10deg' }],
      },
      heartBox: {
        color: 'yellow',
        fontSize: 24,
        width: '50%',
        flex: 2,
        // height: '20%',
        // borderWidth: 3,
        // borderColor: 'white',
        position: 'relative',
        justifyContent: 'center',
        alignItems: 'center',
      },
      heart: {
        width: 140,
        // width: '50%',
        // borderWidth: 3,
        // borderColor: 'white',
        height: '100%',
        // borderRadius: 48,
      },
      hearthText: {
        color: 'white',
        fontSize: 34,
        position: 'absolute',
      },
      Arrow: {
        position: 'absolute',
        top: 100,
        right: 80,
        height: 45,
        width: 45,
      },
});
export default styles;
